apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: co-kafka-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: co-kafka
    spec:
      containers:
        - image: gcr.io/co-gcp/co-kafka
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /co-kafka/healthcheck
              port: 4000
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 1
          name: co-kafka
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /co-kafka/healthcheck
              port: 4000
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 1
          resources:
            limits:
              memory: 256Mi
